config/urls.py
from django.contrib import admin
from django.urls import path,include 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('todolist.urls')),
]

todolist/urls.py
from django.urls import path
from .views import TaskUpdate, Tasklist, TaskDetail
app_name='todolist'

urlpatterns=[
    path('',Tasklist.as_view(),name='task-list'),   
    path('task-create/',TaskDetail.as_view(),name='task-create'),
     path('task/<int:pk>/',TaskDetail.as_view(),name='detailview'),
     path('task-update/<int:pk>',TaskUpdate.as_view(),name='task-update'),
]

todolist/models.py
from tkinter import CASCADE
from django.db import models
from django.contrib.auth.models import User
from sympy import false
from tables import Description
# Create your models here.




class Task(models.Model):
    user=models.ForeignKey(User,on_delete=models.CASCADE,null=True,blank=True)
    title=models.CharField(max_length=200,null=True,blank=True)
    Description=models.TextField(null=True,blank=True)
    compelte=models.BooleanField(default=false)
    created=models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'title{self.title}'

class Meta:
            ordering=['complete']

todolist/views.py
from pyexpat import model
from statistics import mode
from attr import fields
from django.http import HttpResponse
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView,UpdateView,DeleteView
from matplotlib.style import context
# Create your views here.
from .models import Task

class Tasklist(ListView):
    model=Task
    context_object_name='task'
class TaskDetail(DetailView):
    model=Task
    context_object_name='task'
class TaskCreate(CreateView):
    model='task'
    fields='__all__'
    success_url=reverse_lazy('task-list')

class TaskUpdate(UpdateView):
    model='task'

    fields='__all__'

    success_url=reverse_lazy('task-update')

class TaskDelete(DeleteView):
    model='task'
    fields='__all__'
    context_object_name='task'
    

todolist/templates/todolist/task_detail.html
<h1> Hello ITS my To do APP </h1>
<h1>{{task.title}}</h1>
<h1>{{task.description}}</h1>

todolist/templates/todolist/task_form.html
<h1> {{task.description}}</h1>
<form method='POST'action=''>
    {% {% csrf_token %}  %}

    {{form}}
</form>

todolist/templates/todolist/task_list.html
<h1> Hello ITS my To do APP </h1>


<table>
    <tr>
        <th>items</th>
    </tr>
{%  for task in object_list %}
<tr>
    <td>
        {{task.title}}
    </td>

   <td>{% url 'todolist:detailview' task.id%} </td>
   <td>{% url 'todolist:task-create'  %}</td>
   <td> {% url 'todolist:task-update'task.id %}</td>
    
</tr>
{% empty %}
<h3>No items in the List</h3>

<a href=''> Add a new Item</a>
 {% endfor %}
</table>